version: "1"
services:
    nginx:
        restart: always
        build:
            dockerfile: dockerfile
            context: .
        volumes:
            - ./conf:/etc/nginx/conf.d
        ports:
            - "3080:80"
